# Generated by Django 5.1 on 2024-09-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('catagroy', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('MEAT', 'Meat')], max_length=200)),
                ('quantity', models.PositiveIntegerField(max_length=200, null=True)),
            ],
        ),
    ]
