# Generated by Django 5.1 on 2024-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagroy',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('STATIONARY', 'Stationary'), ('ELECTRONIC', 'Electronic'), ('FURNITURE', 'Furniture')], max_length=200, null=True),
        ),
    ]
